name: 'Submodule Notify Parent'

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env:
      PARENT_REPO: lukso-network/tools-wagyu-key-gen
      WORKFLOW_ID: 39950170
    steps:
      - name: Github Update develop
        if: ${{ contains(github.ref, "-develop.") }}
        env:
          PARENT_BRANCH: main
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEVOPS_GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches \
            -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
      - name: Github Update main
        if: ${{ !contains(github.ref, "-develop.") }}
        env:
          PARENT_BRANCH: develop
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEVOPS_GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches \
            -d '{"ref":"${{ env.PARENT_BRANCH }}"}'